-- MySQL Script generated by MySQL Workbench
-- Thu Feb 28 17:49:15 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escola
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `escola` ;

-- -----------------------------------------------------
-- Schema escola
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escola` DEFAULT CHARACTER SET utf8 ;
USE `escola` ;

-- -----------------------------------------------------
-- Table `escola`.`curso`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola`.`curso` ;

CREATE TABLE IF NOT EXISTS `escola`.`curso` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(50) NOT NULL,
  `ementa` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola`.`aluno` ;

CREATE TABLE IF NOT EXISTS `escola`.`aluno` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escola`.`curso_aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `escola`.`curso_aluno` ;

CREATE TABLE IF NOT EXISTS `escola`.`curso_aluno` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `curso_codigo` INT NOT NULL,
  `aluno_codigo` INT NOT NULL,
  PRIMARY KEY (`codigo`, `curso_codigo`, `aluno_codigo`),
  INDEX `fk_curso_aluno_curso_idx` (`curso_codigo` ASC) VISIBLE,
  INDEX `fk_curso_aluno_aluno1_idx` (`aluno_codigo` ASC) VISIBLE,
  CONSTRAINT `fk_curso_aluno_curso`
    FOREIGN KEY (`curso_codigo`)
    REFERENCES `escola`.`curso` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_curso_aluno_aluno1`
    FOREIGN KEY (`aluno_codigo`)
    REFERENCES `escola`.`aluno` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
